// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Travel Managment System",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

// // import "./globals.css";
// // import Link from "next/link";
// // import { ReactNode } from "react";

// // export const metadata = {
// //   title: "Travel App",
// //   description: "Next.js + TypeScript Travel Application",
// // };

// // export default function RootLayout({ children }: { children: ReactNode }) {
// //   return (
// //     <html lang="en">
// //       <body className="flex min-h-screen bg-gray-100">
// //         {/* Sidebar */}
// //         <nav className="w-64 bg-gradient-to-b from-sky-500 to-indigo-600 text-white p-6 flex flex-col space-y-4">
// //           <h1 className="text-2xl font-bold">Travel App</h1>
// //           <Link href="/" className="hover:bg-blue-700 p-2 rounded">Home</Link>
// //           <Link href="/tripdetail" className="hover:bg-blue-700 p-2 rounded">Trip Detail</Link>
// //           <Link href="/payment" className="hover:bg-blue-700 p-2 rounded">Payment</Link>
// //           <Link href="/receipt" className="hover:bg-blue-700 p-2 rounded">Receipt</Link>
// //           <Link href="/about" className="hover:bg-blue-700 p-2 rounded">About</Link>
// //           <Link href="/signup" className="hover:bg-blue-700 p-2 rounded">Signup</Link>
// //         </nav>

// //         {/* Main Content */}
// //         <main className="flex-1">{children}</main>
// //       </body>
// //     </html>
// //   );
// // }

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";  // 👈 import AuthProvider

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Travel Managment System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* 👇 Ab AuthProvider se wrap karna zaroori hai */}
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
